import type { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';
import { requireAuth } from '../middleware/auth.js';
import { createUpload, listUploadParts, signUploadPart, recordUploadPart, completeUpload, attachToMessage, abortUpload, getDownloadUrl } from '../services/file.service.js';
const initSchema=z.object({conversationId:z.string().uuid(),size:z.coerce.bigint().positive(),mime:z.string().max(255).optional(),name:z.string().min(1).max(255)});
const idSchema=z.object({id:z.string().uuid()});
const partSchema=z.object({partNumber:z.coerce.number().int().min(1).max(10000)});
const recordSchema=z.object({partNumber:z.coerce.number().int().min(1).max(10000),etag:z.string().min(1).max(1024),byteSize:z.coerce.number().int().positive().safe()});
export const fileRoutes:FastifyPluginAsync=async(app)=>{
 app.post('/uploads',{preHandler:requireAuth},async(req,reply)=>{const p=initSchema.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'Invalid upload request'});try{return reply.code(201).send(await createUpload(req.auth.userId,p.data));}catch(e){if(e instanceof Error&&e.message==='QUOTA_EXCEEDED')return reply.code(429).send({error:'Daily upload quota exceeded'});if(e instanceof Error&&e.message==='FORBIDDEN')return reply.code(403).send({error:'Not a conversation member'});if(e instanceof Error&&e.message==='FILE_TOO_LARGE')return reply.code(413).send({error:'File exceeds maximum size'});if(e instanceof Error&&e.message==='UNSUPPORTED_MIME')return reply.code(415).send({error:'Unsupported file type'});req.log.error({err:e},'upload initialization failed');return reply.code(500).send({error:'Unable to initialize upload'});}});
 app.get('/uploads/:id/parts',{preHandler:requireAuth},async(req,reply)=>{const p=idSchema.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'Invalid upload id'});try{return reply.send(await listUploadParts(req.auth.userId,p.data.id));}catch(e){if(e instanceof Error&&e.message==='NOT_FOUND')return reply.code(404).send({error:'Upload not found'});if(e instanceof Error&&['UPLOAD_NOT_PENDING','UPLOAD_EXPIRED'].includes(e.message))return reply.code(409).send({error:'Upload unavailable'});return reply.code(500).send({error:'Unable to list upload parts'});}});
 app.post('/uploads/:id/parts',{preHandler:requireAuth},async(req,reply)=>{const p=idSchema.safeParse(req.params);const b=partSchema.safeParse(req.body);if(!p.success||!b.success)return reply.code(400).send({error:'Invalid part request'});try{return reply.send(await signUploadPart(req.auth.userId,p.data.id,b.data.partNumber));}catch(e){if(e instanceof Error&&e.message==='NOT_FOUND')return reply.code(404).send({error:'Upload not found'});if(e instanceof Error&&['INVALID_PART','UPLOAD_NOT_PENDING','UPLOAD_EXPIRED'].includes(e.message))return reply.code(409).send({error:'Invalid upload part'});return reply.code(500).send({error:'Unable to authorize upload part'});}});
 app.put('/uploads/:id/parts',{preHandler:requireAuth},async(req,reply)=>{const p=idSchema.safeParse(req.params);const b=recordSchema.safeParse(req.body);if(!p.success||!b.success)return reply.code(400).send({error:'Invalid uploaded part'});try{return reply.send(await recordUploadPart(req.auth.userId,p.data.id,b.data.partNumber,b.data.etag,b.data.byteSize));}catch(e){if(e instanceof Error&&e.message==='NOT_FOUND')return reply.code(404).send({error:'Upload not found'});if(e instanceof Error&&['INVALID_PART','UPLOAD_NOT_PENDING','UPLOAD_EXPIRED','SIZE_MISMATCH'].includes(e.message))return reply.code(409).send({error:'Invalid uploaded part'});return reply.code(500).send({error:'Unable to record upload part'});}});
 app.post('/uploads/:id/complete',{preHandler:requireAuth},async(req,reply)=>{const p=idSchema.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'Invalid upload id'});try{return reply.send(await completeUpload(req.auth.userId,p.data.id));}catch(e){if(e instanceof Error&&e.message==='NOT_FOUND')return reply.code(404).send({error:'Upload not found'});if(e instanceof Error&&['UPLOAD_NOT_PENDING','UPLOAD_EXPIRED','MISSING_PARTS','SIZE_MISMATCH'].includes(e.message))return reply.code(409).send({error:'Upload cannot be completed'});req.log.error({err:e},'upload completion failed');return reply.code(500).send({error:'Unable to complete upload'});}});
 app.post('/uploads/:id/finalize',{preHandler:requireAuth},async(req,reply)=>{const p=idSchema.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'Invalid upload id'});try{return reply.send(await completeUpload(req.auth.userId,p.data.id));}catch(e){if(e instanceof Error&&e.message==='NOT_FOUND')return reply.code(404).send({error:'Upload not found'});if(e instanceof Error&&['UPLOAD_NOT_PENDING','UPLOAD_EXPIRED','MISSING_PARTS','SIZE_MISMATCH'].includes(e.message))return reply.code(409).send({error:'Upload cannot be finalized'});return reply.code(500).send({error:'Unable to finalize upload'});}});
 app.post('/uploads/:id/attach',{preHandler:requireAuth},async(req,reply)=>{const p=idSchema.safeParse(req.params);const b=z.object({messageId:z.string().uuid()}).safeParse(req.body);if(!p.success||!b.success)return reply.code(400).send({error:'Invalid attachment request'});try{return reply.send(await attachToMessage(req.auth.userId,p.data.id,b.data.messageId));}catch(e){if(e instanceof Error&&e.message==='NOT_FOUND')return reply.code(404).send({error:'Upload not found'});if(e instanceof Error&&['UPLOAD_NOT_COMPLETED','MESSAGE_FORBIDDEN'].includes(e.message))return reply.code(409).send({error:'Attachment cannot be linked'});return reply.code(500).send({error:'Unable to link attachment'});}});
 app.delete('/uploads/:id',{preHandler:requireAuth},async(req,reply)=>{const p=idSchema.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'Invalid upload id'});try{await abortUpload(req.auth.userId,p.data.id);return reply.code(204).send();}catch(e){if(e instanceof Error&&e.message==='NOT_FOUND')return reply.code(404).send({error:'Upload not found'});return reply.code(500).send({error:'Unable to abort upload'});}});
 app.get('/attachments/:id/download',{preHandler:requireAuth},async(req,reply)=>{const p=idSchema.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'Invalid attachment id'});try{return reply.send(await getDownloadUrl(req.auth.userId,p.data.id));}catch(e){if(e instanceof Error&&e.message==='NOT_FOUND')return reply.code(404).send({error:'Attachment not found'});return reply.code(500).send({error:'Unable to authorize download'});}});
};
