import 'package:flutter/material.dart';
import 'feel_it_repository.dart';

class FeelItPage extends StatefulWidget {
  const FeelItPage({super.key,required this.repository});
  final FeelItRepository repository;
  @override State<FeelItPage> createState()=>_FeelItPageState();
}
class _FeelItPageState extends State<FeelItPage>{
  late Future<List<FeelItPost>> _future;
  @override void initState(){super.initState();_reload();}
  void _reload(){_future=widget.repository.list();}
  Future<void> _refresh() async {setState(_reload);await _future;}
  Future<void> _create() async {final result=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,showDragHandle:true,builder:(_)=>_CreateFeelItSheet(repository:widget.repository));if(result==true)setState(_reload);}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Feel It'),actions:[IconButton(onPressed:_create,icon:const Icon(Icons.add_circle_outline),tooltip:'Create Feel It')]),body:RefreshIndicator(onRefresh:_refresh,child:FutureBuilder<List<FeelItPost>>(future:_future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return ListView(children:[Padding(padding:const EdgeInsets.all(32),child:Text('Unable to load Feel It. Pull to retry.',textAlign:TextAlign.center))]);final posts=s.data??const [];if(posts.isEmpty)return ListView(padding:const EdgeInsets.all(16),children:const[_PrivacyNotice(),SizedBox(height:48),_EmptyFeelItState()]);return ListView.builder(padding:const EdgeInsets.all(16),itemCount:posts.length,itemBuilder:(c,i)=>_PostCard(post:posts[i],repository:widget.repository,onDeleted:()=>setState(_reload)));}));
}
class _PrivacyNotice extends StatelessWidget{const _PrivacyNotice();@override Widget build(BuildContext c)=>Card(child:ListTile(leading:const Icon(Icons.lock_outline),title:const Text('Private by default'),subtitle:const Text('Posts expire after 24 hours and visibility is enforced by the server.')));}
class _EmptyFeelItState extends StatelessWidget{const _EmptyFeelItState();@override Widget build(BuildContext c)=>Column(children:[Icon(Icons.auto_awesome_outlined,size:56,color:Theme.of(c).colorScheme.primary),const SizedBox(height:16),Text('Nothing here yet',style:Theme.of(c).textTheme.titleLarge),const SizedBox(height:8),const Text('Share something temporary with the people you choose.',textAlign:TextAlign.center)]);}
class _PostCard extends StatefulWidget{const _PostCard({required this.post,required this.repository,required this.onDeleted});final FeelItPost post;final FeelItRepository repository;final VoidCallback onDeleted;@override State<_PostCard> createState()=>_PostCardState();}
class _PostCardState extends State<_PostCard>{bool busy=false;@override void initState(){super.initState();_view();}Future<void> _view() async{try{await widget.repository.markViewed(widget.post.id);}catch(_){}}Future<void> _react() async{final r=await showDialog<String>(context:context,builder:(c)=>SimpleDialog(title:const Text('React'),children:[for(final x in ['❤️','👍','😂','😮','😢','🔥'])SimpleDialogOption(onPressed:()=>Navigator.pop(c,x),child:Text(x,style:const TextStyle(fontSize:26)))]));if(r!=null){try{await widget.repository.react(widget.post.id,r);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Reaction saved')));}catch(_){}}}Future<void> _reply() async{final controller=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Reply'),content:TextField(controller:controller,maxLength:4000,maxLines:4,decoration:const InputDecoration(hintText:'Write a reply')),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Send'))]));if(ok==true&&controller.text.trim().isNotEmpty){try{await widget.repository.reply(widget.post.id,controller.text);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Reply sent')));}catch(_){}}controller.dispose();}
Future<void> _delete() async{if(widget.post.authorId.isEmpty)return;final yes=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Delete Feel It?'),content:const Text('This removes the post for everyone and revokes its media access.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Delete'))]));if(yes==true){setState(()=>busy=true);try{await widget.repository.delete(widget.post.id);widget.onDeleted();}catch(_){if(mounted)setState(()=>busy=false);}}}
@override Widget build(BuildContext c){final remaining=widget.post.expiresAt.difference(DateTime.now().toUtc());return Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const CircleAvatar(child:Icon(Icons.person_outline)),const SizedBox(width:10),Expanded(child:Text('Shared temporarily',style:Theme.of(c).textTheme.titleMedium)),Text('${remaining.inHours}h left')]),if(widget.post.text!=null)Padding(padding:const EdgeInsets.only(top:14),child:Text(widget.post.text!,style:Theme.of(c).textTheme.bodyLarge)),if(widget.post.attachmentId!=null)const Padding(padding:EdgeInsets.only(top:14),child:ListTile(leading:Icon(Icons.attach_file),title:Text('Private media'),subtitle:Text('Tap to open securely'))),const SizedBox(height:8),Row(children:[IconButton(onPressed:busy?null:_react,icon:const Icon(Icons.favorite_border),tooltip:'React'),IconButton(onPressed:busy?null:_reply,icon:const Icon(Icons.reply_outlined),tooltip:'Reply'),const Spacer(),IconButton(onPressed:busy?null:_delete,icon:const Icon(Icons.delete_outline),tooltip:'Delete')])])));}
}
class _CreateFeelItSheet extends StatefulWidget{const _CreateFeelItSheet({required this.repository});final FeelItRepository repository;@override State<_CreateFeelItSheet> createState()=>_CreateFeelItSheetState();}
class _CreateFeelItSheetState extends State<_CreateFeelItSheet>{final controller=TextEditingController();String visibility='contacts';bool saving=false;@override void dispose(){controller.dispose();super.dispose();}Future<void> _share() async{if(controller.text.trim().isEmpty)return;setState(()=>saving=true);try{await widget.repository.create(text:controller.text,visibility:visibility);if(mounted)Navigator.pop(context,true);}catch(e){if(mounted){setState(()=>saving=false);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Unable to create Feel It')));}}}
@override Widget build(BuildContext c)=>SafeArea(child:Padding(padding:EdgeInsets.fromLTRB(20,8,20,20+MediaQuery.viewInsetsOf(c).bottom),child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:controller,maxLines:4,maxLength:10000,decoration:const InputDecoration(labelText:'What do you feel like sharing?',border:OutlineInputBorder())),const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:visibility,decoration:const InputDecoration(labelText:'Who can see it?',border:OutlineInputBorder()),items:const[DropdownMenuItem(value:'contacts',child:Text('My contacts')),DropdownMenuItem(value:'selected',child:Text('Selected contacts (use API for selection)')),DropdownMenuItem(value:'exclude',child:Text('My contacts except…'))],onChanged:saving?null:(v){if(v!=null)setState(()=>visibility=v);}),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:saving||controller.text.trim().isEmpty?null:_share,icon:saving?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.send),label:Text(saving?'Sharing…':'Share')))]));}
